### ISSUE TITLE
Feature suggestions - fixed header, named busses

### ISSUE THREAD

**Issue by phuvf** [jensstigaard/audio-matrix-vmix-electron#4]
We've been using this app for a while now, and it's been great - the routing visibility is much better than you see in vMix. Congrats on such a great piece of work!

I've a couple of suggestions that would really help us out.

I'm happy to dig into the code myself and write this, but it'll be a few weeks before I have time - so I thought this might be quicker to suggest to you.

**Fix the header row to the top of the window, so it's always visible.**

When we have a long list on inputs (c. 60 is not unusual), scrolling down the list hides the header row. This should be fixed to the page top so it's always visible (similar to freezing rows in Excel)

**Option to name busses**

For every show, each bus has a distinct purpose - e.g. A is _VOIP return_, B is _Comms_, C is _Mix-minus to MediaLooks_. Rather than having to remember these bus assignment, it'd be great to name the busses and have these names appear on the interface. This could be done using a JSON config file - similar to the one I've used to configure OctoCue receiver : <https://octocue.com/receiver_config>, which uses the electron-json-storage module: <https://www.npmjs.com/package/electron-json-storage>

Finally, can I suggest you add a 'Donate' option to your project. There's lots of companies using this to run shows who are happy to support people making useful tools.

Cheers!

**Comment by jensstigaard** [comment]
Hi Nick

I will look at the suggested features later today. 

Out of curiosity can you name any of the companies using the tool?

Thanks

Jens

**Comment by phuvf** [comment]
Since Covid, I've only been working with one client, Fix8Group, in the UK. They've been using it to help control audio on their roster of virtual events - they're also my partners in the OctoCue project.

I'd expect some of my other clients in the UK to be using this, but I haven't done any events for them since we all switched from Barco E2s on stage to vMix and virtual events.

**Comment by jensstigaard** [comment]
Hi Nick - @phuvf

I have just updated the app with the suggested features.

Please download the new release 1.0.0 from https://github.com/jensstigaard/audio-matrix-vmix-electron/releases/ and give it a run.

I look forward to hear your feedback.

**Comment by phuvf** [comment]
Jens,

That all works great - thanks for the update.

Nick

**Comment by jensstigaard** [comment]
@phuvf great! I will close the issue in a couple of days if no further comments have been added at that point.
