### ISSUE TITLE
Issue with Mac running 10.15.7

### ISSUE THREAD

**Issue by BRebels** [jensstigaard/audio-matrix-vmix-electron#5]
When I try to open the Simple vmix switcher & Audio Matrix, I get a pop-up: The application “Audio Matrix vMix Electron” can’t be opened.
Im running my mac on OSX10.15.7

**Comment by jensstigaard** [comment]
Thanks for the report. I am aware of the issue which relates to Mac app Notarization requirements. I will try to resolve the issue soon. Until then, i think it should be possible to run the app by right clicking the .app and choose Open.

**Comment by BRebels** [comment]
Thanks for the quick reply!
I tried with no luck clicking the app and choosing open.

**Comment by jensstigaard** [comment]
Hi @BRebels 

I have now uploaded an updated Mac app release which is "notarized" which should solve the problem. I have tested on my own Macbook, and it works in my end. Please test it out and return with feedback.
Direct link:
https://github.com/jensstigaard/audio-matrix-vmix-electron/releases/download/1.0.0/Audio.Matrix.vMix.Electron-1.0.0.dmg

**Comment by BRebels** [comment]
Jens it is working on my end.
I tried “Simple vMix Switcher” & it seems to be having the same issue as Audio Matrix had.

Thanks

**Comment by jensstigaard** [comment]
@BRebels I will update that app tomorrow resolving same issue. I will post tomorrow when update is uploaded.

**Comment by BRebels** [comment]
Great!
Thanks again Jens.
